export const testdata = {
  keyword: ['Google', 'customer service', 'digital assistant', 'customer', 'user experience', 'voice', 'voice technology'],
  
  title: "Challenge Instructions: Digital Assistants",

  desc: "Digital assistant devices have recently been introduced in the market and consumers are unfamiliar with their actual function. You’ve been hired as a Customer Success Specialist for Google to help customers identify the benefits of purchasing a Google Assistant through voice. Communicate a strong value proposition to the right audience. Remember to record your answers appropriately in each of the four containers. Identify the problem, collect important information from the article (just drag and drop), brainstorm ideas and alternatives, and recommend a final solution in 3-5 sentences. You can use jot notes or write full sentences.",

  res: [
    {
      name: "Use Case: GE Appliances",
      desc: "GE Appliances announced an update to its Wi-Fi connected home appliances, which now work"
      +" directly with Google Assistant, the search giant's voice-powered digital assistant. People can"
      +" say commands like, 'Hey, Google, preheat the oven to 425 degrees,' or ask, 'Hey, Google, are"
      +" my dishes clean?'"
      +"\n"
      +"The direct connection with Google Assistant removes the need to add an additional command"
      +" when talking to GE appliances. Previously, product owners had to use the Geneva Home Action"
      +" for voice commands, such as 'ey Google, ask Geneva Home to preheat the oven to 425"
      +" degrees.'"
      +"\n"
      +"The change works with GE Appliances' connected refrigerators, ovens, dishwashers and"
      +" washing machines, among other home appliances, all linked to the U+ Connect app to manage"
      +" the devices."
      +"\n"
      +"GE Appliances' closer integration with Google Assistant comes as the search giant vies with"
      +" Amazon for dominance in the market for smart home services. The direct connection with the"
      +" digital assistant could make GE home appliances slightly easier to use than with Alexa,"
      +" Amazon's digital assistant that has worked with GE products for the past couple of years."
      +" Amazon and GE in 2016 introduced a Geneva skill for Alexa that requires users say commands"
      +" such as, 'Alexa, tell Geneva to preheat the oven to 350 degrees,' per CNet. This additional step"
      +" may add some friction for users looking for a convenient method of controlling their kitchen's"
      +" smart devices."
      +"\n"
      +"GE Appliances' announcement comes as Electrolux, the Swedish maker of home appliances,"
      +" started integrating its connected kitchen products with Google Assistant. The voice integration"
      +" will begin in smart ovens next year, Electrolux announced last week. With more appliance"
      +" makers experimenting with connected home devices, the technology will continue to evolve and"
      +" grow increasingly sophisticated and easy to use for consumers."
      +"\n"
      +"The digital assistant and smart speaker space continues to heat up. Global shipments of"
      +" voice-powered smart speakers surged 278% to 9.2 million units in Q1 2018 from a year earlier."
      +" While Amazon shipped 4 million of those during the quarter, its market share slipped to 43.6%"
      +" from 81.8% year-over-year, according to Strategy Analytics. The worldwide smart home devices"
      +" market, comprised of smart speakers, digital media adapters, lighting, thermostats and other"
      +" connected gadgets like GE's appliances, is forecast to grow 26.8% this year to 549.5 million"
      +" total shipments, the International Data Corporation estimates."
      +"\n",
    },
    {
      name: "What is Google Assistant?",
      desc: "Google Assistant is Google's voice-controlled smart assistant. It's was"
      +" originally an upgrade or extension of Google Now - designed to be personal -"
      +" while expanding on Google's existing 'OK Google' voice controls."
      +"\n"
      +"Originally, Google Now smartly pulled out relevant information for you: it knew"
      +" where you work, and it knew your meeting locations and travel plans, the sports"
      +" teams you liked, and what interested you so that Now could present you with"
      +" personal information that mattered. Google has long killed the Google Now"
      +" brand, but Assistant very much lives in the same space, but fuses these personalised"
      +" elements with a wide-range of voice control"
      +"\n"
      +"The 'OK Google' or 'Hey, Google' side"
      +" covers voice commands, voice searching,"
      +" and voice-activated device control, letting"
      +" you do things like send messages, check"
      +" appointments and so on on your Android"
      +" device, just like Apple's Siri on an iPhone"
      +" or iPad, but reaching far beyond that, with"
      +" a bot-centric AI experience, designed to"
      +" give you conversational interactions."
      +"\n"
      +"Continued Conversation that means you"
      +" don't have to say 'Hey Google' for"
      +" follow-up requests. Google Assistant will"
      +" also work out when you're talking to it"
      +" versus other people in the room."
      +"\n"
      +"Multiple Actions is also a new capability"
      +" that enables you to ask for multiple things"
      +" at the same time. This, says Google, is"
      +" rather difficult - in linguistics it is called"
      +" coordination reduction. Mastering"
      +" requests like this is probably what will"
      +" power Google Assistant ahead of rivals."
      +"\n"
      +"Also, a new Pretty Please mode for Google"
      +" Assistant will help ensure everyone in"
      +" your household is saying 'please' and"
      +" 'thank you'. When enabled, it responds"
      +" positively when you say either of those"
      +" phrases."
      +"\n"
      +"Pretty Please can be enabled for specific"
      +" members of your household, so you can"
      +" encourage your kids to be polite, or you"
      +" can just play a trick on your spouse as"
      +" they're setting a timer for dinner without"
      +" their manners."
      +"\n"
      +"Because Google Assistant knows you and"
      +" understands context, it can react in an"
      +" informed or smart way. That's important"
      +" as Assistant spreads its wings, because it"
      +" gives voice control a lot more power and"
      +" moves it on from only reacting to specific"
      +" phrases or commands."
      +"\n"
      +"In the future, Google even says that"
      +" Assistant will be able to call and book"
      +" appointments for you."
    }
  ]
};