// Request User repos
export const FETCH_SESSION__START = 'FETCH_SESSION__START';
export const FETCH_SESSION__SUCCESS = 'FETCH_SESSION__SUCCESS';
export const FETCH_SESSION__FAILED = 'FETCH_SESSION__FAILE';
export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const SIGNIN_START = 'SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILED = 'SIGNIN_FAILED';

export const LOAD_A_TEST_START = 'LOAD_A_TEST_START';
export const LOAD_A_TEST_SUCCESS = 'LOAD_A_TEST_SUCCESS';
export const LOAD_A_TEST_FAILED = 'LOAD_A_TEST_FAILED';

export const SUBMIT_TEST_START = 'SUBMIT_TEST_START';
export const SUBMIT_TEST_SUCCESS = 'SUBMIT_TEST_SUCCESS';
export const SUBMIT_TEST_FAILED = 'SUBMIT_TEST_FAILED';
